### ISSUE TITLE
Move to bootcode.bin network boot

### ISSUE THREAD

**Issue by gbaman** [PiNet/PiNet#56]
With the new Raspberry Pi 3 network booting support, a new bootcode.bin has been created by Raspberry Pi Foundation that allows older Pis to also network boot, with just the bootcode.bin on the SD card.
It solves a few issues including
- Out of date boot files. The bootcode.bin is a lot easier to update as just a single file.
- ProxyDHCP based booting, so the server is found automatically. No more to hard code the IP address of the server in cmdline.txt file.
- Far easier editing of boot files by the server admin on the fly. This makes https://github.com/PiNet/PiNet/issues/54 viable.
- Possible support for customised boot files per Pi (based on serial number).
## Todo
- [ ] Investigate support for different Pi versions
  - [x] Pi 1 B - Currently broken, bootcode.bin bug being investigated by Raspberry Pi Foundation.
  - [x] Pi 1 B+ - Works as expected.
  - [x] Pi 2 B - Works as expected.
  - [x] Pi 3 B - Works as expected.
- [x] Investigate booting using initramfs - Looking like is broken, bug being investigated by Raspberry Pi Foundation
- [x] Write PiNet implementation code for setup.
- [ ] Write PiNet IP address update code.
- [ ] Wait until new bootcode.bin is out of testing branch.

**Comment by gbaman** [comment]
Unfortunately this one is still on hold as don't believe has been any movement yet on bootcode.bin support with initramfs. 
Won't be included in initial PiNet Jessie release.

@ghollingworth had any luck with it yet?

**Comment by ghollingworth** [comment]
Still waiting for you to check if it works from an SD card...

**Comment by gbaman** [comment]
Further investigation of this using bootcode.bin and accompanying files (from the ```next``` branch only currently) has it working with all Pis bar the Pi1B.
Initial implementation code for PiNet is ready to go live once Pi1B support is available and boot files are in the main branch.
@ghollingworth any chance of a rough ETA for Pi1B support for booting with bootcode.bin? Would be great to get this out as an option for PiNet users.

**Comment by ghollingworth** [comment]
Pi 1B is now working on latest master branch of firmware

**Comment by gbaman** [comment]
@ghollingworth fantastic! I will have a play over next few days (hopefully) with it.

**Comment by ghollingworth** [comment]
Happy to close now
