### ISSUE TITLE
Investigate "Pixel"

### ISSUE THREAD

**Issue by gbaman** [PiNet/PiNet#60]
With Raspberry Pi having released their new ["Pixel" interface](https://www.raspberrypi.org/blog/introducing-pixel/), investigation is needed to see how it is implemented and more importantly, what it breaks with PiNet Jessie.
Given PiNet stable is still Wheezy, all these new changes won't effect current users, but may effect PiNet Jessie testing servers once apt-get upgrade is done as UI changes have a habit of breaking some PiNet stuff.
## TODO
- [x] Investigate changes with [Pi-Gen](https://github.com/RPi-Distro/pi-gen) since last Raspbian release.
- [x] Figure out which packages have been changed with Pixel, is there perhaps a new package for it?
- [x] Check with a fresh install of PiNet Jessie, if any of the Pixel stuff right now breaks it.
- [x] Implement new UI changes/icons.

**Comment by gbaman** [comment]
So after few hours investigating the changes, there is a few issues already. One in particular with the new pix-plym-splash package, which will cause PiNet Jessie to fail to install the raspberrypi-ui-mods as is now marked as a dependency of it.
Besides that, the UI updates don't seem to have broken the PiNet UI and after fixing the other issue, seems to work fine.

After playing around with it for 5-10 mins, can also say the new menu bar icons seem to be causing issues. Have had the menu bar crash when moving mouse over "other" and also had icons completely missing.
![img_8021](https://cloud.githubusercontent.com/assets/833193/18936009/e541b0fc-85db-11e6-9b80-d20efcfe7d28.JPG)

**Comment by gbaman** [comment]
The above issue has sine been fixed it looks like and all the new packages have now been implemented in with https://github.com/PiNet/PiNet/commit/ea1fdf9af13e5689c262419d18ddb5c0ffded6a8.

Still need to consider best approach for https://github.com/PiNet/PiNet/issues/62.

**Comment by gbaman** [comment]
Raspbian Jessie Pixel has now been fully implemented in PiNet Jessie Alpha.
